name: flutter_analyze_and_test

on:
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - '**'

env:
  JAVA_VERSION: 12.x
  FLUTTER_VERSION: 2.2.3

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup
      run: make setup

    - name: Analyze
      if: always()
      run: make analyze

    - name: Test
      if: always()
      run: make test