name: flutter_analyze_and_test

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Get Pachages
        run: flutter pub get
      - name: Generate Files
        run: flutter pub run build_runner build --delete-conflicting-outputs~
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: flutter test --verbose